[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "hello_world"
path = "src/main.rs"

[dependencies]
chrono = "0.4.23"
marine-rs-sdk = "0.7.1"
serde = "1.0.152"
serde_json = "1.0.92"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
