[package]
name = "sqlite_facade"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "sqlite_facade"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
marine-sqlite-connector = "0.6.0"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
